import com.github.spotbugs.snom.Effort
import com.github.spotbugs.snom.SpotBugsTask

plugins {
    id 'java'
    id 'pmd'
    id 'org.springframework.boot' version '4.1.0'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'com.github.spotbugs' version '6.5.10'
}

group = 'com.cicd'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'

    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    spotbugsPlugins 'com.h3xstream.findsecbugs:findsecbugs-plugin:1.13.0'
}

pmd {
    toolVersion = "7.3.0"
    ignoreFailures = true
}

spotbugs {
    ignoreFailures = true
    effort = Effort.MAX
    showStackTraces = true
}

tasks.register('unit-tests', Test) {
    classpath = sourceSets.test.runtimeClasspath
    testClassesDirs = sourceSets.test.output.classesDirs

    useJUnitPlatform()

    filter {
        includeTestsMatching "*UnitTest"
    }
}

tasks.named('test') {
    useJUnitPlatform()
}

tasks.withType(SpotBugsTask).configureEach {
    reports {
        html.required = true
    }
}

tasks.withType(Pmd).configureEach {
    reports {
        html.required = true
        xml.required = false
    }
}